// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2TDc2x6aHGtzDVUj-hYH4DndqTu7A6Q',
    appId: '1:1405097634:web:66d6428471b984fe6169fb',
    messagingSenderId: '1405097634',
    projectId: 'instagram-clone-5e088',
    authDomain: 'instagram-clone-5e088.firebaseapp.com',
    storageBucket: 'instagram-clone-5e088.appspot.com',
    measurementId: 'G-0YQPMV1J5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDon-EwQQ-WU-WlAEMzju8s76PfqhAl3BU',
    appId: '1:1405097634:android:c55e2fd1add5db766169fb',
    messagingSenderId: '1405097634',
    projectId: 'instagram-clone-5e088',
    storageBucket: 'instagram-clone-5e088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG1nq9JsangufKyenrwowvix-AbJBjsQc',
    appId: '1:1405097634:ios:c9af5f7993fe97126169fb',
    messagingSenderId: '1405097634',
    projectId: 'instagram-clone-5e088',
    storageBucket: 'instagram-clone-5e088.appspot.com',
    iosBundleId: 'com.example.instagramClon',
  );
}
